/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import the component file

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as BlogImport } from './routes/blog'
import { Route as AdminImport } from './routes/admin'
import { Route as AdminPostsImport } from './routes/admin.posts'
import { Route as AdminMediaImport } from './routes/admin.media'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const BlogRoute = BlogImport.update({
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const AdminPostsRoute = AdminPostsImport.update({
  path: '/admin/posts',
  getParentRoute: () => rootRoute,
} as any)

const AdminMediaRoute = AdminMediaImport.update({
  path: '/admin/media',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/admin/posts': {
      preLoaderRoute: typeof AdminPostsImport
      parentRoute: typeof rootRoute
    }
    '/admin/media': {
      preLoaderRoute: typeof AdminMediaImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      preLoaderRoute: typeof BlogImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AdminRoute,
  AdminPostsRoute,
  AdminMediaRoute,
  BlogRoute,
  LoginRoute,
])

/* prettier-ignore-end */